name: Monitor Workflow

on: [push, workflow_dispatch]

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run monitoring script
      env:
        MAX_ATTEMPTS: 3
      run: |
        attempt=0
        while [ $attempt -lt $MAX_ATTEMPTS ]; do
          python monitor.py && break
          attempt=$((attempt+1))
          if [ $attempt -lt $MAX_ATTEMPTS ]; then
            echo "Attempt $attempt failed. Retrying in 60 seconds..."
            sleep 60
          else
            echo "All attempts failed"
            exit 1
          fi
        done
        echo "📡✅ Monitoring script executed successfully"

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: monitor-logs
        path: logs/*.log