name: Website Monitor
on:
  schedule:
    - cron: '*/13 * * * *'  # Runs every 13 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run monitoring script
      run: python monitor.py